#pragma once
#define MK_3_SPEED 1
#define MK_C_OFFSET_0 4
#define MK_C_OFFSET_1 16
#define MK_C_OFFSET_2 32

#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_TRANSACTION_IDS_USER SENTENCE_CASE_SYNC, SENTENCE_CASE_PRIMED_SYNC, LEADER_SYNC
#define RGB_TRIGGER_ON_KEYDOWN

// Ploopy auto-mouse timing
#define PLOOPY_ACTIVITY_TIMEOUT_MS 300
#define PLOOPY_LED_BEACON_WINDOW_MS 120

// RGB matrix sleep behavior
#define RGB_MATRIX_TIMEOUT 300000
#define RGB_MATRIX_SLEEP
#define RGB_DISABLE_WHEN_USB_SUSPENDED

// Home row definitions
#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_F18
#define TAPPING_TERM 250
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD
#define FLOW_TAP_TERM 150

#define DEBOUNCE 20

// Timing constants
#define APP_SWITCHER_TIMEOUT 750

#define QUICK_TAP_TERM 0

#define CAPS_WORD_IDLE_TIMEOUT 8000

// Leader key configuration
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 350
#define LEADER_NO_TIMEOUT

// Prevent not loading master/slave
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 5000
#define SPLIT_USB_TIMEOUT_POLL 10
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 5500
